[package]
name = "mongodb-cursor-pagination"
version = "0.2.9"
authors = ["Kylian Lichtensteiger <e38c1a93@srylax.dev"]
edition = "2021"
license = "MIT"
keywords = ["mongo", "mongodb", "database", "cursor", "pagination"]
readme = "README.md"
repository = "https://github.com/Srylax/mongodb-cursor-pagination"
description = """
Provides cursor based pagination for the native MongoDB driver in Rust.
"""

[features]
default = []
graphql = ["juniper"]

[dependencies]
base64 = "0.12.3"
bson = "0.14.1"
log = "0.4.11"
mongodb = "0.9.2"
serde = "1.0"
juniper = { version = "0.14.2", optional = true }

